---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "all"
  gather_facts: false
  tasks:

    - name: "Get Apache2 service current state"
      register: install_apache_service_status
      failed_when: not install_apache_service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "apache2"

    - name: "Check Apache2 folders and conf"
      loop:
        - "/etc/apache2/apache2.conf"
        - "/etc/apache2/ports.conf"
      loop_control:
        loop_var: folder_path
      register: folder_check
      failed_when: not folder_check.stat.exists
      ansible.builtin.stat:
        path: "{{ folder_path }}"

    - name: "Check Apache2 HTTP connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_install_apache_http_listen_port }}"
        timeout: 120

    - name: "Check Apache2 HTTPS connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_install_apache_https_listen_port }}"
        timeout: 120
