---
install_apache_https_listen_port: 443
install_apache_http_listen_port: 80

install_apache_group: "www-data"
install_apache_user: "www-data"

install_apache_modules:
  - "ssl"
  - "rewrite"
  - "filter"
  - "headers"

install_apache_remove_all_vhosts: true
install_apache_loglevel: "info"

install_apache_enable_qos: false
install_apache_enable_security: false
install_apache_enable_evasive: false
install_apache_enable_pagespeed: false
install_apache_enable_prefork: true

install_apache_security_core_version: "3.3.0"
install_apache_security_version: "3.0.10"

install_apache_mpm_start_servers: 1
install_apache_mpm_min_spare_servers: 3
install_apache_mpm_max_spare_servers: 3
install_apache_mpm_max_request_workers: 20 # 512 MB / 20 MB = 25.6
install_apache_mpm_max_connections_per_child: 5000
