---

- name: "Deploy Nextcloud from sources"
  notify:
    - "Reload Apache2"
  ansible.builtin.unarchive:
    dest: "{{ install_nextcloud_data_path }}"
    src: "https://download.nextcloud.com/server/releases/latest.zip"
    owner: "{{ install_nextcloud_apache_system_user }}"
    group: "{{ install_nextcloud_apache_system_group }}"
    mode: "0755"
    remote_src: yes

- name: "Import config.php"
  notify:
    - "Reload Apache2"
    - "Restart php-fpmRestart php-fpm"
  ansible.builtin.template:
    src: "templates/config.php.j2"
    dest: "{{ install_nextcloud_data_path }}/config/config.php"
    owner: "{{ install_nextcloud_apache_system_user }}"
    group: "{{ install_nextcloud_apache_system_group }}"
    mode: "0755"
