---
add_certificates_tmp_workspace: "/tmp/add_certificates"
add_certificates_ca_location: "/usr/local/share/ca-certificates"

add_certificates_bundle_name: "My-CA-Authority"
add_certificates_bundle_type: "CA"
add_certificates_bundle_src: "/tmp/ssl/{{ add_certificates_bundle_name }}.zip"
add_certificates_bundle_dest: "/tmp/deployed_ssl"
add_certificates_bundle_src_user: "myUser"
add_certificates_bundle_src_password: "secretPassword"
add_certificates_bundle_dest_user: "root"
add_certificates_bundle_dest_group: "root"
add_certificates_bundle_dest_mode: "0755"

add_certificates_artifactory_login: "myUser"
add_certificates_artifactory_password: "myUserPassword"
