---
- name: "Import pools"
  notify: "Restart php-fpm"
  block:
    - name: "Import all pools"
      loop: "{{ add_php_fpm_confs_fpm_pools }}"
      loop_control:
        loop_var: pool
      ansible.builtin.template:
        src: "templates/pool.conf.j2"
        dest: "{{ add_php_fpm_confs_php_pools_path }}/{{ pool.name }}.conf"
        mode: "0700"
        owner: "root"
        group: "root"
        lstrip_blocks: yes
