---
- name: "Reload Apache2"
  register: install_apache__service_status
  changed_when: install_apache__service_status.state != "reloaded"
  ansible.builtin.service:
    name: "apache2"
    state: "reloaded"
