---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_nextcloud"
      tags:
        - "labocbz.install_nextcloud"
      vars:
        install_nextcloud_install_path: "{{ inv_install_nextcloud_install_path }}"
        install_nextcloud_install_data_path: "{{ inv_install_nextcloud_install_data_path }}"
        install_nextcloud_apache_system_user: "{{ inv_install_nextcloud_apache_system_user }}"
        install_nextcloud_apache_system_group: "{{ inv_install_nextcloud_apache_system_group }}"
        install_nextcloud_version: "{{ inv_install_nextcloud_version }}"
        install_nextcloud_default_locale: "{{ inv_install_nextcloud_default_locale }}"
        install_nextcloud_default_phone_region: "{{ inv_install_nextcloud_default_phone_region }}"
        install_nextcloud_default_timezone: "{{ inv_install_nextcloud_default_timezone }}"
        install_nextcloud_loglevel: "{{ inv_install_nextcloud_loglevel }}"
        install_nextcloud_debug: "{{ inv_install_nextcloud_debug }}"
        install_nextcloud_mysql_database: "{{ inv_install_nextcloud_mysql_database }}"
        install_nextcloud_mysql_user: "{{ inv_install_nextcloud_mysql_user }}"
        install_nextcloud_mysql_password: "{{ inv_install_nextcloud_mysql_password }}"
        install_nextcloud_mysql_host: "{{ inv_install_nextcloud_mysql_host }}"
        install_nextcloud_mysql_port: "{{ inv_install_nextcloud_mysql_port }}"
        install_nextcloud_mysql_attr_ssl_key: "{{ inv_install_nextcloud_mysql_attr_ssl_key }}"
        install_nextcloud_mysql_attr_ssl_crt: "{{ inv_install_nextcloud_mysql_attr_ssl_crt }}"
        install_nextcloud_mysql_attr_ssl_ca: "{{ inv_install_nextcloud_mysql_attr_ssl_ca }}"
        install_nextcloud_mysql_attr_ssl_verify_server_cert: "{{ inv_install_nextcloud_mysql_attr_ssl_verify_server_cert }}"
        install_nextcloud_redis_host: "{{ inv_install_nextcloud_redis_host }}"
        install_nextcloud_redis_password: "{{ inv_install_nextcloud_redis_password }}"
        install_nextcloud_trusted_proxies: "{{ inv_install_nextcloud_trusted_proxies }}"
        install_nextcloud_trusted_domains: "{{ inv_install_nextcloud_trusted_domains }}"
        install_nextcloud_overwritehost: "{{ inv_install_nextcloud_overwritehost }}"
        install_nextcloud_owerwriteprotocol: "{{ inv_install_nextcloud_owerwriteprotocol }}"
        install_nextcloud_owerwritecliurl: "{{ inv_install_nextcloud_owerwritecliurl }}"
        #
        install_nextcloud_instanceid: "{{ inv_install_nextcloud_instanceid }}"
        install_nextcloud_passwordsalt: "{{ inv_install_nextcloud_passwordsalt }}"
        install_nextcloud_secret: "{{ inv_install_nextcloud_secret }}"
      ansible.builtin.include_role:
        name: "labocbz.install_nextcloud"
