---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "local"
  gather_facts: false
  tasks:

    - name: "Get Apache2 service current state"
      register: install_apache__service_status
      failed_when: not install_apache__service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "apache2"

    - name: "Check Nextcloud folders and conf"
      loop:
        - "{{ inv_install_nextcloud__install_path }}"
        - "{{ inv_install_nextcloud__install_data_path }}"
        - "{{ inv_install_nextcloud__install_path }}/nextcloud"
        - "{{ inv_install_nextcloud__install_path }}/nextcloud/config"
      loop_control:
        loop_var: folder_path
      register: folder_check
      failed_when: not folder_check.stat.exists
      ansible.builtin.stat:
        path: "{{ folder_path }}"

    - name: "Check Apache2 HTTP connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "80"
        timeout: 120

    - name: "Check Apache2 HTTPS connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "443"
        timeout: 120
