---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:


    - name: "Include labocbz.install_nextcloud"
      tags:
        - "labocbz.install_nextcloud"
      vars:
        install_nextcloud__install_path: "{{ inv_install_nextcloud__install_path }}"
        install_nextcloud__install_data_path: "{{ inv_install_nextcloud__install_data_path }}"
        install_nextcloud__apache_system_user: "{{ inv_install_nextcloud__apache_system_user }}"
        install_nextcloud__apache_system_group: "{{ inv_install_nextcloud__apache_system_group }}"
        install_nextcloud__version: "{{ inv_install_nextcloud__version }}"
        install_nextcloud__default_locale: "{{ inv_install_nextcloud__default_locale }}"
        install_nextcloud__default_phone_region: "{{ inv_install_nextcloud__default_phone_region }}"
        install_nextcloud__default_timezone: "{{ inv_install_nextcloud__default_timezone }}"
        install_nextcloud__loglevel: "{{ inv_install_nextcloud__loglevel }}"
        install_nextcloud__debug: "{{ inv_install_nextcloud__debug }}"
        install_nextcloud__mysql_database: "{{ inv_install_nextcloud__mysql_database }}"
        install_nextcloud__mysql_user: "{{ inv_install_nextcloud__mysql_user }}"
        install_nextcloud__mysql_password: "{{ inv_install_nextcloud__mysql_password }}"
        install_nextcloud__mysql_host: "{{ inv_install_nextcloud__mysql_host }}"
        install_nextcloud__mysql_port: "{{ inv_install_nextcloud__mysql_port }}"
        install_nextcloud__mysql_attr_ssl_key: "{{ inv_install_nextcloud__mysql_attr_ssl_key }}"
        install_nextcloud__mysql_attr_ssl_crt: "{{ inv_install_nextcloud__mysql_attr_ssl_crt }}"
        install_nextcloud__mysql_attr_ssl_ca: "{{ inv_install_nextcloud__mysql_attr_ssl_ca }}"
        install_nextcloud__mysql_attr_ssl_verify_server_cert: "{{ inv_install_nextcloud__mysql_attr_ssl_verify_server_cert }}"
        install_nextcloud__redis_host: "{{ inv_install_nextcloud__redis_host }}"
        install_nextcloud__redis_port: "{{ inv_install_nextcloud__redis_port }}"
        install_nextcloud__redis_password: "{{ inv_install_nextcloud__redis_password }}"
        install_nextcloud__trusted_proxies: "{{ inv_install_nextcloud__trusted_proxies }}"
        install_nextcloud__trusted_domains: "{{ inv_install_nextcloud__trusted_domains }}"
        install_nextcloud__overwritehost: "{{ inv_install_nextcloud__overwritehost }}"
        install_nextcloud__owerwriteprotocol: "{{ inv_install_nextcloud__owerwriteprotocol }}"
        install_nextcloud__owerwritecliurl: "{{ inv_install_nextcloud__owerwritecliurl }}"
        install_nextcloud__admin_user: "{{ inv_install_nextcloud__admin_user }}"
        install_nextcloud__admin_password: "{{ inv_install_nextcloud__admin_password }}"
        install_nextcloud__clean_cron_file: "{{ inv_install_nextcloud__clean_cron_file }}"
        #
        install_nextcloud__mail_from_address: "{{ inv_install_nextcloud__mail_from_address }}"
        install_nextcloud__mail_smtpmode: "{{ inv_install_nextcloud__mail_smtpmode }}"
        install_nextcloud__mail_sendmailmode: "{{ inv_install_nextcloud__mail_sendmailmode }}"
        install_nextcloud__mail_domain: "{{ inv_install_nextcloud__mail_domain }}"
        install_nextcloud__mail_smtphost: "{{ inv_install_nextcloud__mail_smtphost }}"
        install_nextcloud__mail_smtpport: "{{ inv_install_nextcloud__mail_smtpport }}"
        #
        install_nextcloud__instanceid: "{{ inv_install_nextcloud__instanceid }}"
        install_nextcloud__passwordsalt: "{{ inv_install_nextcloud__passwordsalt }}"
        install_nextcloud__secret: "{{ inv_install_nextcloud__secret }}"
      ansible.builtin.include_role:
        name: "labocbz.install_nextcloud"
