- name: "Enable and start MariaDB"
  register: install_mariadb_service_status
  changed_when: not install_mariadb_service_status.state != "started"
  throttle: 1
  ansible.builtin.service:
    name: "mariadb"
    state: "started"
    daemon_reload: true
    enabled: yes

- name: "Restart MariaDB"
  register: install_mariadb_service_status
  changed_when: not install_mariadb_service_status.state != "restarted"
  throttle: 1
  ansible.builtin.service:
    name: "mariadb"
    state: "restarted"
    daemon_reload: true
    enabled: yes
