---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.add_apache_confs"
      tags:
        - "labocbz.add_apache_confs"
      vars:
        add_apache_confs_http_listen_port: "{{ inv_add_apache_confs_http_listen_port }}"
        add_apache_confs_https_listen_port: "{{ inv_add_apache_confs_https_listen_port }}"
        add_apache_confs_ldap_url: "{{ inv_add_apache_confs_ldap_url }}"
        add_apache_confs_ldap_port: "{{ inv_add_apache_confs_ldap_port }}"
        add_apache_confs_ldap_dc: "{{ inv_add_apache_confs_ldap_dc }}"
        add_apache_confs_auth_ldap_url: "{{ inv_add_apache_confs_auth_ldap_url }}"
        add_apache_confs_custom_ldap_base_header: "{{ inv_add_apache_confs_custom_ldap_base_header }}"
        add_apache_confs_webmaster: "{{ inv_add_apache_confs_webmaster }}"
        add_apache_confs_request_body: "{{ inv_add_apache_confs_request_body }}"
        add_apache_confs_security_body_limit: "{{ inv_add_apache_confs_security_body_limit }}"
        add_apache_confs_ssl_files_path: "{{ inv_add_apache_confs_ssl_files_path }}"
        add_apache_confs_conf_path: "{{ inv_add_apache_confs_conf_path }}"
        add_apache_confs_base_document_root: "{{ inv_add_apache_confs_base_document_root }}"
        add_apache_confs_configurations: "{{ inv_add_apache_confs_configurations }}"
      ansible.builtin.include_role:
        name: "labocbz.add_apache_confs"
