---
add_apache_confs_http_listen_port: 80
add_apache_confs_https_listen_port: 443

add_apache_confs_apache_group: "www-data"
add_apache_confs_apache_user: "www-data"

add_apache_confs_ldap_url: "ldap.your.domain"
add_apache_confs_ldap_port: 389
add_apache_confs_ldap_dc: "DC=sub,DC=domain,DC=net"
add_apache_confs_auth_ldap_url: "ldap://{{ add_apache_confs_ldap_url }}:{{ add_apache_confs_ldap_port }}/OU=People,{{ add_apache_confs_ldap_dc }}?uid"
add_apache_confs_custom_ldap_base_header: "ldap-auth"

add_apache_confs_webmaster: "your.webmaster@domain.tld"
add_apache_confs_request_body: 0
add_apache_confs_security_body_limit: 1024000000

add_apache_confs_ssl_files_path: "/etc/apache2/ssl"
add_apache_confs_conf_path: "/etc/apache2/sites-available"
add_apache_confs_base_document_root: "/var/www/html"

add_apache_confs_configurations:
  - server:
      name: "my-apache-site-1.domain.tld"
      aliases:
        - "oneAlias.net"
        - "anotherAlias.com"
      webmaster: "{{ add_apache_confs_webmaster }}"
    ssl:
      enabled: true
      key: "{{ add_apache_confs_ssl_files_path }}/my-apache-site-1.domain.tld/my-apache-site-1.domain.tld.pem.key"
      crt: "{{ add_apache_confs_ssl_files_path }}/my-apache-site-1.domain.tld/my-apache-site-1.domain.tld.pem.crt"
    proxy:
      url: "https://my.proxy"
      pass: "/"
    security:
      disabled: true
      request_body: 4096000
      sec_rules_remove_by_id:
        - 980130
        - 933120
    rewrites:
      - ^/\.well-known/carddav /remote.php/dav [R=301,L]
      - ^/\.well-known/caldav /remote.php/dav [R=301,L]
      - ^/\.well-known/webfinger /index.php/.well-known/webfinger [R=301,L]
      - ^/\.well-known/nodeinfo /index.php/.well-known/nodeinfo [R=301,L]
    redirect: "http://my.newest.site.net"
    ldap:
      url: "{{ add_apache_confs_auth_ldap_url }}"
      attribute: "memberUid"
      attribute_is_dn: "off"
      dc: "{{ add_apache_confs_ldap_dc }}"
      groups:
        - admin
        - users
      exception_base_urls:
        - /api
    custom_confs:
        - name: "phpmyadmin.j2"
          alias:
            url: "/"
            path: "/usr/share/phpmyadmin"
          install_path: "/usr/share/phpmyadmin"
        